"""
Seed script for NYC local resources (hospitals, pediatricians, daycares).

Run with:
    python -m app.seed.seed_local_resources
"""

from app.database import Base, engine, SessionLocal
from app.models.local_resource import LocalResource


RESOURCES = [
    # ======================================================================
    # HOSPITALS
    # ======================================================================
    {
        "name": "Mount Sinai Hospital",
        "category": "hospital",
        "neighborhood": "Upper East Side",
        "address": "1 Gustave L. Levy Pl, New York, NY 10029",
        "phone": "(212) 241-6500",
        "website": "https://www.mountsinai.org",
        "hours": "24/7 Emergency",
        "description": "Major academic medical center with a top-ranked pediatrics department and Level IV NICU.",
        "rating": 4.5,
        "accepts_insurance": True,
        "latitude": 40.7900,
        "longitude": -73.9526,
    },
    {
        "name": "NewYork-Presbyterian / Weill Cornell",
        "category": "hospital",
        "neighborhood": "Upper East Side",
        "address": "525 E 68th St, New York, NY 10065",
        "phone": "(212) 746-5454",
        "website": "https://www.nyp.org",
        "hours": "24/7 Emergency",
        "description": "World-renowned hospital with an exceptional pediatric emergency department and neonatal care.",
        "rating": 4.6,
        "accepts_insurance": True,
        "latitude": 40.7651,
        "longitude": -73.9540,
    },
    {
        "name": "Lenox Hill Hospital",
        "category": "hospital",
        "neighborhood": "Upper East Side",
        "address": "100 E 77th St, New York, NY 10075",
        "phone": "(212) 434-2000",
        "website": "https://www.northwell.edu/lenox-hill-hospital",
        "hours": "24/7 Emergency",
        "description": "Full-service hospital known for maternity and newborn services with a Level III NICU.",
        "rating": 4.3,
        "accepts_insurance": True,
        "latitude": 40.7738,
        "longitude": -73.9594,
    },
    {
        "name": "Mount Sinai West",
        "category": "hospital",
        "neighborhood": "Midtown",
        "address": "1000 10th Ave, New York, NY 10019",
        "phone": "(212) 523-4000",
        "website": "https://www.mountsinai.org/locations/mount-sinai-west",
        "hours": "24/7 Emergency",
        "description": "Comprehensive hospital with labor & delivery, pediatric ER, and newborn nursery.",
        "rating": 4.2,
        "accepts_insurance": True,
        "latitude": 40.7695,
        "longitude": -73.9900,
    },
    {
        "name": "NewYork-Presbyterian Lower Manhattan Hospital",
        "category": "hospital",
        "neighborhood": "Financial District",
        "address": "170 William St, New York, NY 10038",
        "phone": "(212) 312-5000",
        "website": "https://www.nyp.org/lowermanhattan",
        "hours": "24/7 Emergency",
        "description": "Community hospital in Lower Manhattan with maternity services and pediatric care.",
        "rating": 4.1,
        "accepts_insurance": True,
        "latitude": 40.7093,
        "longitude": -74.0064,
    },
    {
        "name": "NYC Health + Hospitals / Harlem",
        "category": "hospital",
        "neighborhood": "Harlem",
        "address": "506 Lenox Ave, New York, NY 10037",
        "phone": "(212) 939-1000",
        "website": "https://www.nychealthandhospitals.org/harlem",
        "hours": "24/7 Emergency",
        "description": "Public hospital serving the Harlem community with pediatric and maternity services. Accepts all insurance including Medicaid.",
        "rating": 3.8,
        "accepts_insurance": True,
        "latitude": 40.8141,
        "longitude": -73.9400,
    },
    {
        "name": "NewYork-Presbyterian Allen Hospital",
        "category": "hospital",
        "neighborhood": "Washington Heights",
        "address": "5141 Broadway, New York, NY 10034",
        "phone": "(212) 932-4000",
        "website": "https://www.nyp.org/allen",
        "hours": "24/7 Emergency",
        "description": "Community hospital with family-centered maternity care and a well-baby nursery.",
        "rating": 4.0,
        "accepts_insurance": True,
        "latitude": 40.8681,
        "longitude": -73.9226,
    },
    {
        "name": "Lenox Health Greenwich Village",
        "category": "hospital",
        "neighborhood": "Greenwich Village",
        "address": "30 7th Ave, New York, NY 10011",
        "phone": "(212) 434-3700",
        "website": "https://www.northwell.edu/lenox-health-greenwich-village",
        "hours": "24/7 Emergency",
        "description": "Free-standing emergency department with pediatric urgent care services.",
        "rating": 4.2,
        "accepts_insurance": True,
        "latitude": 40.7372,
        "longitude": -73.9996,
    },

    # ======================================================================
    # PEDIATRICIANS
    # ======================================================================
    {
        "name": "Tribeca Pediatrics - Upper West Side",
        "category": "pediatrician",
        "neighborhood": "Upper West Side",
        "address": "210 W 96th St, New York, NY 10025",
        "phone": "(212) 226-7666",
        "website": "https://www.tribecapediatrics.com",
        "hours": "Mon-Fri 8am-8pm, Sat-Sun 9am-1pm",
        "description": "Modern pediatric practice with extended hours and same-day sick visits. Newborn through adolescence.",
        "rating": 4.7,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7946,
        "longitude": -73.9718,
    },
    {
        "name": "Westside Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Upper West Side",
        "address": "620 Columbus Ave, New York, NY 10024",
        "phone": "(212) 874-1245",
        "website": "https://www.westsidepediatricsnyc.com",
        "hours": "Mon-Fri 8:30am-5pm, Sat 9am-12pm",
        "description": "Established pediatric group providing well-baby checkups, vaccinations, and developmental screenings.",
        "rating": 4.5,
        "accepts_insurance": True,
        "age_range": "0-21 years",
        "latitude": 40.7853,
        "longitude": -73.9735,
    },
    {
        "name": "Park East Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Upper East Side",
        "address": "1245 Park Ave, New York, NY 10128",
        "phone": "(212) 427-0540",
        "website": "https://www.parkeastpediatrics.com",
        "hours": "Mon-Fri 8am-6pm, Sat 9am-12pm",
        "description": "Board-certified pediatricians specializing in newborn care and early childhood development.",
        "rating": 4.6,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7846,
        "longitude": -73.9528,
    },
    {
        "name": "Tribeca Pediatrics - Tribeca",
        "category": "pediatrician",
        "neighborhood": "Tribeca",
        "address": "40 Hudson St, New York, NY 10013",
        "phone": "(212) 226-7666",
        "website": "https://www.tribecapediatrics.com",
        "hours": "Mon-Fri 8am-8pm, Sat-Sun 9am-5pm",
        "description": "Flagship location of the popular pediatric group. Walk-in sick visits and lactation support available.",
        "rating": 4.8,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7192,
        "longitude": -74.0100,
    },
    {
        "name": "Greenwich Village Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Greenwich Village",
        "address": "67 Irving Pl, New York, NY 10003",
        "phone": "(212) 529-4330",
        "website": "https://www.gvpediatrics.com",
        "hours": "Mon-Fri 9am-5pm",
        "description": "Small-practice pediatric office offering personalized care for newborns and children.",
        "rating": 4.4,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7345,
        "longitude": -73.9884,
    },
    {
        "name": "Chelsea Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Chelsea",
        "address": "133 W 22nd St, New York, NY 10011",
        "phone": "(212) 924-2290",
        "website": "https://www.chelseapediatricsnyc.com",
        "hours": "Mon-Fri 8:30am-5:30pm, Sat 9am-12pm",
        "description": "Family-friendly pediatric practice providing comprehensive well-child visits and immunizations.",
        "rating": 4.5,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7419,
        "longitude": -73.9949,
    },
    {
        "name": "East Village Pediatrics",
        "category": "pediatrician",
        "neighborhood": "East Village",
        "address": "225 E 12th St, New York, NY 10003",
        "phone": "(212) 475-5500",
        "website": "https://www.evpediatrics.com",
        "hours": "Mon-Fri 9am-5pm",
        "description": "Neighborhood pediatric office with a focus on developmental milestones and breastfeeding support.",
        "rating": 4.3,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7309,
        "longitude": -73.9870,
    },
    {
        "name": "SoHo Pediatrics",
        "category": "pediatrician",
        "neighborhood": "SoHo",
        "address": "568 Broadway, Suite 402, New York, NY 10012",
        "phone": "(212) 334-3016",
        "website": "https://www.sohopediatrics.com",
        "hours": "Mon-Fri 8:30am-5pm",
        "description": "Boutique pediatric practice known for attentive newborn and infant care.",
        "rating": 4.6,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7235,
        "longitude": -73.9975,
    },
    {
        "name": "Harlem Pediatric Associates",
        "category": "pediatrician",
        "neighborhood": "Harlem",
        "address": "215 W 125th St, New York, NY 10027",
        "phone": "(212) 222-3500",
        "website": "https://www.harlempediatrics.com",
        "hours": "Mon-Fri 9am-5pm, Sat 9am-1pm",
        "description": "Community-oriented pediatric practice serving Harlem families. Accepts Medicaid and most major insurance.",
        "rating": 4.2,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.8082,
        "longitude": -73.9480,
    },
    {
        "name": "Washington Heights Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Washington Heights",
        "address": "4141 Broadway, New York, NY 10033",
        "phone": "(212) 928-3700",
        "website": "https://www.whpediatricsnyc.com",
        "hours": "Mon-Fri 8:30am-5pm",
        "description": "Bilingual (English/Spanish) pediatric practice serving families in Washington Heights and Inwood.",
        "rating": 4.3,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.8490,
        "longitude": -73.9345,
    },
    {
        "name": "Lower East Side Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Lower East Side",
        "address": "227 E Broadway, New York, NY 10002",
        "phone": "(212) 233-5500",
        "website": "https://www.lespediatrics.com",
        "hours": "Mon-Fri 9am-5pm",
        "description": "Welcoming practice providing newborn care, vaccinations, and developmental screenings to LES families.",
        "rating": 4.1,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7138,
        "longitude": -73.9864,
    },
    {
        "name": "Midtown Pediatrics",
        "category": "pediatrician",
        "neighborhood": "Midtown",
        "address": "315 W 57th St, New York, NY 10019",
        "phone": "(212) 265-5500",
        "website": "https://www.midtownpediatricsnyc.com",
        "hours": "Mon-Fri 8am-6pm",
        "description": "Convenient Midtown location offering comprehensive pediatric services including lactation consultation.",
        "rating": 4.4,
        "accepts_insurance": True,
        "age_range": "0-18 years",
        "latitude": 40.7662,
        "longitude": -73.9835,
    },

    # ======================================================================
    # DAYCARES
    # ======================================================================
    {
        "name": "Bright Horizons - Upper West Side",
        "category": "daycare",
        "neighborhood": "Upper West Side",
        "address": "100 W 93rd St, New York, NY 10025",
        "phone": "(212) 875-2300",
        "website": "https://www.brighthorizons.com",
        "hours": "Mon-Fri 7:30am-6pm",
        "description": "National chain offering infant and toddler programs with low teacher-to-child ratios.",
        "rating": 4.4,
        "accepts_insurance": False,
        "age_range": "6 weeks - 5 years",
        "latitude": 40.7935,
        "longitude": -73.9707,
    },
    {
        "name": "The Shark Bites Learning Center",
        "category": "daycare",
        "neighborhood": "Upper East Side",
        "address": "1482 First Ave, New York, NY 10075",
        "phone": "(212) 249-2211",
        "website": "https://www.sharkbiteslearning.com",
        "hours": "Mon-Fri 8am-6pm",
        "description": "Play-based early learning center with dedicated infant rooms and sensory activities.",
        "rating": 4.3,
        "accepts_insurance": False,
        "age_range": "3 months - 5 years",
        "latitude": 40.7713,
        "longitude": -73.9525,
    },
    {
        "name": "Vivvi - Tribeca",
        "category": "daycare",
        "neighborhood": "Tribeca",
        "address": "25 Park Pl, New York, NY 10007",
        "phone": "(646) 883-8483",
        "website": "https://www.vivvi.com",
        "hours": "Mon-Fri 7:30am-6:30pm",
        "description": "Modern childcare center with a research-backed curriculum for infants and toddlers.",
        "rating": 4.7,
        "accepts_insurance": False,
        "age_range": "3 months - 5 years",
        "latitude": 40.7129,
        "longitude": -74.0073,
    },
    {
        "name": "Little Maestros",
        "category": "daycare",
        "neighborhood": "Chelsea",
        "address": "154 W 14th St, New York, NY 10011",
        "phone": "(212) 929-4110",
        "website": "https://www.littlemaestronyc.com",
        "hours": "Mon-Fri 8am-6pm",
        "description": "Music-enriched early childhood program with a warm, nurturing environment for infants.",
        "rating": 4.5,
        "accepts_insurance": False,
        "age_range": "3 months - 4 years",
        "latitude": 40.7380,
        "longitude": -73.9984,
    },
    {
        "name": "Village Kids Nursery",
        "category": "daycare",
        "neighborhood": "Greenwich Village",
        "address": "123 W 4th St, New York, NY 10012",
        "phone": "(212) 533-2120",
        "website": "https://www.villagekidsnursery.com",
        "hours": "Mon-Fri 8am-5:30pm",
        "description": "Cozy neighborhood nursery program focused on social-emotional development and creative play.",
        "rating": 4.4,
        "accepts_insurance": False,
        "age_range": "6 months - 4 years",
        "latitude": 40.7314,
        "longitude": -74.0000,
    },
    {
        "name": "Little Sprouts Learning Center",
        "category": "daycare",
        "neighborhood": "East Village",
        "address": "95 Avenue A, New York, NY 10009",
        "phone": "(212) 477-2255",
        "website": "https://www.littlesproutsev.com",
        "hours": "Mon-Fri 7:30am-6pm",
        "description": "Community-based daycare with outdoor play space and a focus on nature-based learning.",
        "rating": 4.2,
        "accepts_insurance": False,
        "age_range": "3 months - 5 years",
        "latitude": 40.7264,
        "longitude": -73.9839,
    },
    {
        "name": "Sunshine Learning Center",
        "category": "daycare",
        "neighborhood": "Lower East Side",
        "address": "55 Norfolk St, New York, NY 10002",
        "phone": "(212) 475-8800",
        "website": "https://www.sunshineles.com",
        "hours": "Mon-Fri 7:30am-6pm",
        "description": "Affordable daycare program with bilingual staff and a structured infant curriculum.",
        "rating": 4.0,
        "accepts_insurance": False,
        "age_range": "6 weeks - 5 years",
        "latitude": 40.7183,
        "longitude": -73.9867,
    },
    {
        "name": "SoHo Baby Academy",
        "category": "daycare",
        "neighborhood": "SoHo",
        "address": "475 Broome St, New York, NY 10013",
        "phone": "(212) 334-2255",
        "website": "https://www.sohobabyacademy.com",
        "hours": "Mon-Fri 8am-6pm",
        "description": "Premium childcare with small class sizes, dedicated infant room, and Reggio Emilia-inspired program.",
        "rating": 4.6,
        "accepts_insurance": False,
        "age_range": "3 months - 5 years",
        "latitude": 40.7229,
        "longitude": -73.9999,
    },
    {
        "name": "Harlem Children's Zone Midtown Center",
        "category": "daycare",
        "neighborhood": "Harlem",
        "address": "35 E 125th St, New York, NY 10035",
        "phone": "(212) 360-3255",
        "website": "https://www.hcz.org",
        "hours": "Mon-Fri 8am-6pm",
        "description": "Community-centered early childhood program with comprehensive family support services. Sliding-scale fees.",
        "rating": 4.3,
        "accepts_insurance": False,
        "age_range": "6 weeks - 5 years",
        "latitude": 40.8076,
        "longitude": -73.9405,
    },
    {
        "name": "Little Heights Daycare",
        "category": "daycare",
        "neighborhood": "Washington Heights",
        "address": "600 W 178th St, New York, NY 10033",
        "phone": "(212) 781-5500",
        "website": "https://www.littleheightsdaycare.com",
        "hours": "Mon-Fri 7:30am-6pm",
        "description": "Bilingual daycare (English/Spanish) with ACS voucher acceptance and UPK partnership.",
        "rating": 4.1,
        "accepts_insurance": False,
        "age_range": "6 weeks - 5 years",
        "latitude": 40.8492,
        "longitude": -73.9350,
    },
    {
        "name": "Midtown Kids Academy",
        "category": "daycare",
        "neighborhood": "Midtown",
        "address": "350 W 42nd St, New York, NY 10036",
        "phone": "(212) 563-7700",
        "website": "https://www.midtownkidsacademy.com",
        "hours": "Mon-Fri 7:30am-6:30pm",
        "description": "Conveniently located childcare center near Times Square with flexible scheduling for working parents.",
        "rating": 4.2,
        "accepts_insurance": False,
        "age_range": "3 months - 5 years",
        "latitude": 40.7579,
        "longitude": -73.9919,
    },
    {
        "name": "FiDi Family Daycare",
        "category": "daycare",
        "neighborhood": "Financial District",
        "address": "80 John St, New York, NY 10038",
        "phone": "(212) 571-1100",
        "website": "https://www.fidifamily.com",
        "hours": "Mon-Fri 7:30am-6:30pm",
        "description": "Downtown daycare serving Financial District families with infant and toddler programs.",
        "rating": 4.3,
        "accepts_insurance": False,
        "age_range": "3 months - 5 years",
        "latitude": 40.7084,
        "longitude": -74.0060,
    },
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        existing = db.query(LocalResource).count()
        if existing:
            print(f"Found {existing} existing resources — clearing and re-seeding.")
            db.query(LocalResource).delete()
            db.commit()

        for r in RESOURCES:
            db.add(LocalResource(**r))
        db.commit()
        print(f"Seeded {len(RESOURCES)} local resources.")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
